#pragma once
// This file is needed to import the obs.h header (normaly it is generated by cmake, but i am not using that).
#define OBS_INSTALL_PREFIX ""
#define OBS_PLUGIN_PATH    ""
#define OBS_DATA_PATH      ""

#define GIO_FOUND
#define PULSEAUDIO_FOUND
#define XCB_XINPUT_FOUND
#define ENABLE_WAYLAND

#define OBS_RELEASE_CANDIDATE false
#define OBS_BETA false